# docker-compose.yml
version: '3.8'
services:
  mysqldb:
    image: mysql:8.3
    env_file: ./.env
    environment:
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - 3308:3306
    logging:
      driver: none
  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 3301:3300