# docker-compose.yml
version: '3.8'
services:
  mysqldb:
    image: mysql:8.3
    env_file: ./.env
    environment:
      - MYSQL_USER=nando
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=home
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3308:3306
    logging:
      driver: none
  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 3301:3300